version: '3'

services:
  go-weather:
    container_name: go-weather
    build: 
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1